// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkmdgtupxnqiwewemtby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrbWRndHVweG5xaXdld2VtdGJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgyNDg3MTUsImV4cCI6MjA5MzgyNDcxNX0.Fh7wRx2gLzEt2-hchkGg2JseySKTCN1QX2rhLsliSeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});